import type { Nation, NationConfederation, NationGeo } from '../types'
import nationsJson from './nations.json'
import geoJson from './nation-geo.json'

/** Generated by scripts/build-map.mjs - edit the script, not these files. */
export const NATIONS = nationsJson as readonly Nation[]
export const NATION_GEO = geoJson as unknown as Readonly<Record<string, NationGeo>>

export const NATION_BY_CODE: ReadonlyMap<string, Nation> = new Map(
  NATIONS.map((nation) => [nation.code, nation]),
)

/** Confederations in the order they are shown, most nations first. */
export const NATION_CONFEDERATIONS = ['UEFA', 'CAF', 'AFC', 'CONCACAF', 'OFC', 'CONMEBOL'] as const

export const CONFEDERATION_REGIONS: Readonly<Record<NationConfederation, string>> = {
  UEFA: 'Europe',
  CAF: 'Africa',
  AFC: 'Asia & Oceania',
  CONCACAF: 'North & Central America',
  OFC: 'Oceania',
  CONMEBOL: 'South America',
}
